version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8090:80"  # Mapea el puerto 8090 en el host al puerto 80 del contenedor
    environment:
      SPRING_APPLICATION_NAME: luiscastillo-market
      SPRING_PROFILES_ACTIVE: pdn
      SERVER_SERVLET_CONTEXT_PATH: /luiscastillo-market/api
      SERVER_PORT: 80  # Asegúrate de que tu aplicación escuche en el puerto 80
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/lcmarket
      SPRING_DATASOURCE_USERNAME: luisjaviercastillorabanal
      SPRING_DATASOURCE_PASSWORD: ""  # (deja vacío si no tienes contraseña)
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: lcmarket
      POSTGRES_USER: luisjaviercastillorabanal
      POSTGRES_PASSWORD: ""  # Contraseña vacía según tu configuración actual
    ports:
      - "5432:5432"  # Expone PostgreSQL en el puerto 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
